tasks:
  - name: Install Dependencies and Start Server
    init: |
      yes | npm create vite@latest bucketlistapp --assume-yes -- --template react
      cd bucketlistapp
      npm install
      npm create amplify@latest -y
   # command: |
   #   npm run dev
  #  rails s -b 0.0.0.0 # Starts a Ruby on Rails server accessible externally
